// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v3.21.12
// source: pkg/api/scheduler.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AddJobRequest struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Id      string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Payload string                 `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	// Kita gunakan timestamp standar dari protobuf
	ScheduleTime        *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=schedule_time,json=scheduleTime,proto3" json:"schedule_time,omitempty"`
	RepeatIntervalNanos int64                  `protobuf:"varint,4,opt,name=repeat_interval_nanos,json=repeatIntervalNanos,proto3" json:"repeat_interval_nanos,omitempty"`
	MaxRuns             int32                  `protobuf:"varint,5,opt,name=max_runs,json=maxRuns,proto3" json:"max_runs,omitempty"`
	MaxRetries          int32                  `protobuf:"varint,6,opt,name=max_retries,json=maxRetries,proto3" json:"max_retries,omitempty"`
	InitialBackoffNanos int64                  `protobuf:"varint,7,opt,name=initial_backoff_nanos,json=initialBackoffNanos,proto3" json:"initial_backoff_nanos,omitempty"`
	MaxBackoffNanos     int64                  `protobuf:"varint,8,opt,name=max_backoff_nanos,json=maxBackoffNanos,proto3" json:"max_backoff_nanos,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *AddJobRequest) Reset() {
	*x = AddJobRequest{}
	mi := &file_pkg_api_scheduler_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddJobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddJobRequest) ProtoMessage() {}

func (x *AddJobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_scheduler_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddJobRequest.ProtoReflect.Descriptor instead.
func (*AddJobRequest) Descriptor() ([]byte, []int) {
	return file_pkg_api_scheduler_proto_rawDescGZIP(), []int{0}
}

func (x *AddJobRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AddJobRequest) GetPayload() string {
	if x != nil {
		return x.Payload
	}
	return ""
}

func (x *AddJobRequest) GetScheduleTime() *timestamppb.Timestamp {
	if x != nil {
		return x.ScheduleTime
	}
	return nil
}

func (x *AddJobRequest) GetRepeatIntervalNanos() int64 {
	if x != nil {
		return x.RepeatIntervalNanos
	}
	return 0
}

func (x *AddJobRequest) GetMaxRuns() int32 {
	if x != nil {
		return x.MaxRuns
	}
	return 0
}

func (x *AddJobRequest) GetMaxRetries() int32 {
	if x != nil {
		return x.MaxRetries
	}
	return 0
}

func (x *AddJobRequest) GetInitialBackoffNanos() int64 {
	if x != nil {
		return x.InitialBackoffNanos
	}
	return 0
}

func (x *AddJobRequest) GetMaxBackoffNanos() int64 {
	if x != nil {
		return x.MaxBackoffNanos
	}
	return 0
}

type AddJobResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	AssignedNode  string                 `protobuf:"bytes,3,opt,name=assigned_node,json=assignedNode,proto3" json:"assigned_node,omitempty"` // Memberitahu node mana yang akhirnya memegang job ini
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddJobResponse) Reset() {
	*x = AddJobResponse{}
	mi := &file_pkg_api_scheduler_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddJobResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddJobResponse) ProtoMessage() {}

func (x *AddJobResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_scheduler_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddJobResponse.ProtoReflect.Descriptor instead.
func (*AddJobResponse) Descriptor() ([]byte, []int) {
	return file_pkg_api_scheduler_proto_rawDescGZIP(), []int{1}
}

func (x *AddJobResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *AddJobResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *AddJobResponse) GetAssignedNode() string {
	if x != nil {
		return x.AssignedNode
	}
	return ""
}

var File_pkg_api_scheduler_proto protoreflect.FileDescriptor

const file_pkg_api_scheduler_proto_rawDesc = "" +
	"\n" +
	"\x17pkg/api/scheduler.proto\x12\x03api\x1a\x1fgoogle/protobuf/timestamp.proto\"\xca\x02\n" +
	"\rAddJobRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\apayload\x18\x02 \x01(\tR\apayload\x12?\n" +
	"\rschedule_time\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\fscheduleTime\x122\n" +
	"\x15repeat_interval_nanos\x18\x04 \x01(\x03R\x13repeatIntervalNanos\x12\x19\n" +
	"\bmax_runs\x18\x05 \x01(\x05R\amaxRuns\x12\x1f\n" +
	"\vmax_retries\x18\x06 \x01(\x05R\n" +
	"maxRetries\x122\n" +
	"\x15initial_backoff_nanos\x18\a \x01(\x03R\x13initialBackoffNanos\x12*\n" +
	"\x11max_backoff_nanos\x18\b \x01(\x03R\x0fmaxBackoffNanos\"i\n" +
	"\x0eAddJobResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12#\n" +
	"\rassigned_node\x18\x03 \x01(\tR\fassignedNode2E\n" +
	"\x10SchedulerService\x121\n" +
	"\x06AddJob\x12\x12.api.AddJobRequest\x1a\x13.api.AddJobResponseB(Z&github.com/vnmchuo/gocron-dist/pkg/apib\x06proto3"

var (
	file_pkg_api_scheduler_proto_rawDescOnce sync.Once
	file_pkg_api_scheduler_proto_rawDescData []byte
)

func file_pkg_api_scheduler_proto_rawDescGZIP() []byte {
	file_pkg_api_scheduler_proto_rawDescOnce.Do(func() {
		file_pkg_api_scheduler_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_api_scheduler_proto_rawDesc), len(file_pkg_api_scheduler_proto_rawDesc)))
	})
	return file_pkg_api_scheduler_proto_rawDescData
}

var file_pkg_api_scheduler_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_pkg_api_scheduler_proto_goTypes = []any{
	(*AddJobRequest)(nil),         // 0: api.AddJobRequest
	(*AddJobResponse)(nil),        // 1: api.AddJobResponse
	(*timestamppb.Timestamp)(nil), // 2: google.protobuf.Timestamp
}
var file_pkg_api_scheduler_proto_depIdxs = []int32{
	2, // 0: api.AddJobRequest.schedule_time:type_name -> google.protobuf.Timestamp
	0, // 1: api.SchedulerService.AddJob:input_type -> api.AddJobRequest
	1, // 2: api.SchedulerService.AddJob:output_type -> api.AddJobResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_pkg_api_scheduler_proto_init() }
func file_pkg_api_scheduler_proto_init() {
	if File_pkg_api_scheduler_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_api_scheduler_proto_rawDesc), len(file_pkg_api_scheduler_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_api_scheduler_proto_goTypes,
		DependencyIndexes: file_pkg_api_scheduler_proto_depIdxs,
		MessageInfos:      file_pkg_api_scheduler_proto_msgTypes,
	}.Build()
	File_pkg_api_scheduler_proto = out.File
	file_pkg_api_scheduler_proto_goTypes = nil
	file_pkg_api_scheduler_proto_depIdxs = nil
}
